# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/202/ibek.ioc.schema.json

ioc_name: bl01t-ea-ioc-02
description: Example simulated camera for BL01T

entities:
  - type: ADSimDetector.simDetector
    PORT: det.cam
    P: BL01T-EA-TST-03
    R: ":CAM:"

  - type: ADCore.NDPvaPlugin
    PORT: det.pva
    PVNAME: BL01T-EA-TST-03:PVA:OUTPUT
    P: BL01T-EA-TST-03
    R: ":PVA:"
    NDARRAY_PORT: det.cam

  - type: ADCore.NDROI
    NDARRAY_PORT: det.cam
    P: BL01T-EA-TST-03
    PORT: det.roi
    R: ":ROI:"

  - type: ADCore.NDFileHDF5
    NDARRAY_PORT: det.cam
    P: BL01T-EA-TST-03
    PORT: det.hdf
    R: ":HDF5:"
