services:

  ca-gateway: &ca-gateway

    container_name: ca-gateway

    image: ghcr.io/epics-containers/docker-ca-gateway:2.1.3ec1

    expose:
      - 5064-5065/udp
      - 5064-5065

    ports:
      # bind to localhost to isolate channel access to this host only
      - 127.0.0.1:5064:5064/udp
      - 127.0.0.1:5064-5065:5064-5065

    restart: unless-stopped

    networks:
      channel_access:

    configs:
      - source: ca-gateway_config
        target: /config

    command: -cip 172.20.255.255 -pvlist /config/pvlist -access /config/access -log /dev/stdout -debug 1

configs:
  ca-gateway_config:
    file: ./config

include:
  - path:
      ../../include/networks.yml
